ALTER TABLE words ADD COLUMN language VARCHAR(2) NOT NULL DEFAULT 'en';
ALTER TABLE words DROP CONSTRAINT IF EXISTS unique_word;
ALTER TABLE words ADD CONSTRAINT unique_word UNIQUE (text, category, language);

-- Insert 20 English words for each of the 14 categories
INSERT INTO words (text, category, language) VALUES
-- Movies
('Inception', 'Movies', 'en'),
('Interstellar', 'Movies', 'en'),
('Gladiator', 'Movies', 'en'),
('Titanic', 'Movies', 'en'),
('The Matrix', 'Movies', 'en'),
('Avatar', 'Movies', 'en'),
('Pulp Fiction', 'Movies', 'en'),
('The Godfather', 'Movies', 'en'),
('Jaws', 'Movies', 'en'),
('Star Wars', 'Movies', 'en'),
('Parasite', 'Movies', 'en'),
('The Lion King', 'Movies', 'en'),
('Goodfellas', 'Movies', 'en'),
('Jurassic Park', 'Movies', 'en'),
('Fight Club', 'Movies', 'en'),
('The Dark Knight', 'Movies', 'en'),
('Frozen', 'Movies', 'en'),
('Toy Story', 'Movies', 'en'),
('Blade Runner', 'Movies', 'en'),
('Shrek', 'Movies', 'en'),

-- Football players
('Lionel Messi', 'Football players', 'en'),
('Cristiano Ronaldo', 'Football players', 'en'),
('Kylian Mbappe', 'Football players', 'en'),
('Erling Haaland', 'Football players', 'en'),
('Kevin De Bruyne', 'Football players', 'en'),
('Mohamed Salah', 'Football players', 'en'),
('Neymar Jr', 'Football players', 'en'),
('Harry Kane', 'Football players', 'en'),
('Robert Lewandowski', 'Football players', 'en'),
('Luka Modric', 'Football players', 'en'),
('Jude Bellingham', 'Football players', 'en'),
('Vinicius Jr', 'Football players', 'en'),
('Karim Benzema', 'Football players', 'en'),
('Virgil van Dijk', 'Football players', 'en'),
('Antoine Griezmann', 'Football players', 'en'),
('Bruno Fernandes', 'Football players', 'en'),
('Son Heung-min', 'Football players', 'en'),
('Alisson Becker', 'Football players', 'en'),
('Bukayo Saka', 'Football players', 'en'),
('Zlatan Ibrahimovic', 'Football players', 'en'),

-- Football teams
('Real Madrid', 'Football teams', 'en'),
('Manchester City', 'Football teams', 'en'),
('Liverpool', 'Football teams', 'en'),
('Barcelona', 'Football teams', 'en'),
('Bayern Munich', 'Football teams', 'en'),
('Arsenal', 'Football teams', 'en'),
('Manchester United', 'Football teams', 'en'),
('Paris Saint-Germain', 'Football teams', 'en'),
('Inter Milan', 'Football teams', 'en'),
('AC Milan', 'Football teams', 'en'),
('Chelsea', 'Football teams', 'en'),
('Juventus', 'Football teams', 'en'),
('Atletico Madrid', 'Football teams', 'en'),
('Borussia Dortmund', 'Football teams', 'en'),
('Bayer Leverkusen', 'Football teams', 'en'),
('Tottenham Hotspur', 'Football teams', 'en'),
('Napoli', 'Football teams', 'en'),
('Ajax', 'Football teams', 'en'),
('Benfica', 'Football teams', 'en'),
('Aston Villa', 'Football teams', 'en'),

-- Disney characters
('Mickey Mouse', 'Disney characters', 'en'),
('Donald Duck', 'Disney characters', 'en'),
('Simba', 'Disney characters', 'en'),
('Cinderella', 'Disney characters', 'en'),
('Snow White', 'Disney characters', 'en'),
('Aladdin', 'Disney characters', 'en'),
('Ariel', 'Disney characters', 'en'),
('Goofy', 'Disney characters', 'en'),
('Belle', 'Disney characters', 'en'),
('Mulan', 'Disney characters', 'en'),
('Buzz Lightyear', 'Disney characters', 'en'),
('Woody', 'Disney characters', 'en'),
('Elsa', 'Disney characters', 'en'),
('Olaf', 'Disney characters', 'en'),
('Stitch', 'Disney characters', 'en'),
('Peter Pan', 'Disney characters', 'en'),
('Pocahontas', 'Disney characters', 'en'),
('Hercules', 'Disney characters', 'en'),
('Winnie the Pooh', 'Disney characters', 'en'),
('Maleficent', 'Disney characters', 'en'),

-- Superheroes
('Superman', 'Superheroes', 'en'),
('Batman', 'Superheroes', 'en'),
('Wonder Woman', 'Superheroes', 'en'),
('Spider-Man', 'Superheroes', 'en'),
('Iron Man', 'Superheroes', 'en'),
('Captain America', 'Superheroes', 'en'),
('The Flash', 'Superheroes', 'en'),
('Black Widow', 'Superheroes', 'en'),
('Thor', 'Superheroes', 'en'),
('Hulk', 'Superheroes', 'en'),
('Aquaman', 'Superheroes', 'en'),
('Green Lantern', 'Superheroes', 'en'),
('Doctor Strange', 'Superheroes', 'en'),
('Black Panther', 'Superheroes', 'en'),
('Wolverine', 'Superheroes', 'en'),
('Daredevil', 'Superheroes', 'en'),
('Green Arrow', 'Superheroes', 'en'),
('Supergirl', 'Superheroes', 'en'),
('Shazam', 'Superheroes', 'en'),
('Deadpool', 'Superheroes', 'en'),

-- Rock bands
('The Beatles', 'Rock bands', 'en'),
('Led Zeppelin', 'Rock bands', 'en'),
('Queen', 'Rock bands', 'en'),
('Pink Floyd', 'Rock bands', 'en'),
('The Rolling Stones', 'Rock bands', 'en'),
('AC/DC', 'Rock bands', 'en'),
('Nirvana', 'Rock bands', 'en'),
('Guns N Roses', 'Rock bands', 'en'),
('Metallica', 'Rock bands', 'en'),
('Red Hot Chili Peppers', 'Rock bands', 'en'),
('The Who', 'Rock bands', 'en'),
('U2', 'Rock bands', 'en'),
('Radiohead', 'Rock bands', 'en'),
('Linkin Park', 'Rock bands', 'en'),
('Green Day', 'Rock bands', 'en'),
('Arctic Monkeys', 'Rock bands', 'en'),
('Coldplay', 'Rock bands', 'en'),
('Foo Fighters', 'Rock bands', 'en'),
('Fleetwood Mac', 'Rock bands', 'en'),
('Deep Purple', 'Rock bands', 'en'),

-- TV shows
('Breaking Bad', 'TV shows', 'en'),
('Game of Thrones', 'TV shows', 'en'),
('Friends', 'TV shows', 'en'),
('The Office', 'TV shows', 'en'),
('Stranger Things', 'TV shows', 'en'),
('The Sopranos', 'TV shows', 'en'),
('Succession', 'TV shows', 'en'),
('Better Call Saul', 'TV shows', 'en'),
('Black Mirror', 'TV shows', 'en'),
('The Bear', 'TV shows', 'en'),
('The Last of Us', 'TV shows', 'en'),
('Sherlock', 'TV shows', 'en'),
('Narcos', 'TV shows', 'en'),
('The Wire', 'TV shows', 'en'),
('The Mandalorian', 'TV shows', 'en'),
('Peaky Blinders', 'TV shows', 'en'),
('Dark', 'TV shows', 'en'),
('Seinfeld', 'TV shows', 'en'),
('House of the Dragon', 'TV shows', 'en'),
('The Simpsons', 'TV shows', 'en'),

-- Celebrities
('Tom Cruise', 'Celebrities', 'en'),
('Taylor Swift', 'Celebrities', 'en'),
('Beyonce', 'Celebrities', 'en'),
('Leonardo DiCaprio', 'Celebrities', 'en'),
('Rihanna', 'Celebrities', 'en'),
('Brad Pitt', 'Celebrities', 'en'),
('Dwayne Johnson', 'Celebrities', 'en'),
('Selena Gomez', 'Celebrities', 'en'),
('Elon Musk', 'Celebrities', 'en'),
('Kim Kardashian', 'Celebrities', 'en'),
('Margot Robbie', 'Celebrities', 'en'),
('Zendaya', 'Celebrities', 'en'),
('Will Smith', 'Celebrities', 'en'),
('Lady Gaga', 'Celebrities', 'en'),
('Justin Bieber', 'Celebrities', 'en'),
('Scarlett Johansson', 'Celebrities', 'en'),
('Keanu Reeves', 'Celebrities', 'en'),
('Ryan Reynolds', 'Celebrities', 'en'),
('Ariana Grande', 'Celebrities', 'en'),
('Meryl Streep', 'Celebrities', 'en'),

-- Historical figures
('Albert Einstein', 'Historical figures', 'en'),
('Leonardo da Vinci', 'Historical figures', 'en'),
('Napoleon Bonaparte', 'Historical figures', 'en'),
('Julius Caesar', 'Historical figures', 'en'),
('Cleopatra', 'Historical figures', 'en'),
('Abraham Lincoln', 'Historical figures', 'en'),
('Mahatma Gandhi', 'Historical figures', 'en'),
('Nelson Mandela', 'Historical figures', 'en'),
('Winston Churchill', 'Historical figures', 'en'),
('Martin Luther King Jr', 'Historical figures', 'en'),
('Isaac Newton', 'Historical figures', 'en'),
('Marie Curie', 'Historical figures', 'en'),
('Alexander the Great', 'Historical figures', 'en'),
('Genghis Khan', 'Historical figures', 'en'),
('George Washington', 'Historical figures', 'en'),
('Christopher Columbus', 'Historical figures', 'en'),
('Joan of Arc', 'Historical figures', 'en'),
('Queen Victoria', 'Historical figures', 'en'),
('Rosa Parks', 'Historical figures', 'en'),
('Charles Darwin', 'Historical figures', 'en'),

-- Marvel heroes
('Iron Man', 'Marvel heroes', 'en'),
('Spider-Man', 'Marvel heroes', 'en'),
('Captain America', 'Marvel heroes', 'en'),
('Thor', 'Marvel heroes', 'en'),
('Black Widow', 'Marvel heroes', 'en'),
('Hulk', 'Marvel heroes', 'en'),
('Doctor Strange', 'Marvel heroes', 'en'),
('Black Panther', 'Marvel heroes', 'en'),
('Scarlet Witch', 'Marvel heroes', 'en'),
('Ant-Man', 'Marvel heroes', 'en'),
('Captain Marvel', 'Marvel heroes', 'en'),
('Star-Lord', 'Marvel heroes', 'en'),
('Groot', 'Marvel heroes', 'en'),
('Hawkeye', 'Marvel heroes', 'en'),
('Vision', 'Marvel heroes', 'en'),
('Falcon', 'Marvel heroes', 'en'),
('Winter Soldier', 'Marvel heroes', 'en'),
('Wolverine', 'Marvel heroes', 'en'),
('Deadpool', 'Marvel heroes', 'en'),
('Daredevil', 'Marvel heroes', 'en'),

-- Rappers
('Eminem', 'Rappers', 'en'),
('Drake', 'Rappers', 'en'),
('Kendrick Lamar', 'Rappers', 'en'),
('Kanye West', 'Rappers', 'en'),
('Jay-Z', 'Rappers', 'en'),
('Travis Scott', 'Rappers', 'en'),
('Lil Wayne', 'Rappers', 'en'),
('J Cole', 'Rappers', 'en'),
('Post Malone', 'Rappers', 'en'),
('Snoop Dogg', 'Rappers', 'en'),
('Ice Cube', 'Rappers', 'en'),
('Dr Dre', 'Rappers', 'en'),
('Nicki Minaj', 'Rappers', 'en'),
('Cardi B', 'Rappers', 'en'),
('Future', 'Rappers', 'en'),
('21 Savage', 'Rappers', 'en'),
('Tyler the Creator', 'Rappers', 'en'),
('A$AP Rocky', 'Rappers', 'en'),
('Doja Cat', 'Rappers', 'en'),
('Jack Harlow', 'Rappers', 'en'),

-- YouTubers
('MrBeast', 'YouTubers', 'en'),
('PewDiePie', 'YouTubers', 'en'),
('Markiplier', 'YouTubers', 'en'),
('Jacksepticeye', 'YouTubers', 'en'),
('Casey Neistat', 'YouTubers', 'en'),
('Marques Brownlee', 'YouTubers', 'en'),
('Dream', 'YouTubers', 'en'),
('Logan Paul', 'YouTubers', 'en'),
('Jake Paul', 'YouTubers', 'en'),
('Sidemen', 'YouTubers', 'en'),
('Dude Perfect', 'YouTubers', 'en'),
('Ibai', 'YouTubers', 'en'),
('Speed', 'YouTubers', 'en'),
('Emma Chamberlain', 'YouTubers', 'en'),
('Veritasium', 'YouTubers', 'en'),
('Kurzgesagt', 'YouTubers', 'en'),
('Ninja', 'YouTubers', 'en'),
('Pokimane', 'YouTubers', 'en'),
('Lilly Singh', 'YouTubers', 'en'),
('James Charles', 'YouTubers', 'en'),

-- Car brands
('Toyota', 'Car brands', 'en'),
('Tesla', 'Car brands', 'en'),
('Ferrari', 'Car brands', 'en'),
('BMW', 'Car brands', 'en'),
('Mercedes-Benz', 'Car brands', 'en'),
('Audi', 'Car brands', 'en'),
('Ford', 'Car brands', 'en'),
('Honda', 'Car brands', 'en'),
('Porsche', 'Car brands', 'en'),
('Lamborghini', 'Car brands', 'en'),
('Chevrolet', 'Car brands', 'en'),
('Volkswagen', 'Car brands', 'en'),
('Hyundai', 'Car brands', 'en'),
('Nissan', 'Car brands', 'en'),
('Lexus', 'Car brands', 'en'),
('McLaren', 'Car brands', 'en'),
('Aston Martin', 'Car brands', 'en'),
('Jeep', 'Car brands', 'en'),
('Subaru', 'Car brands', 'en'),
('Mazda', 'Car brands', 'en'),

-- Video games
('Minecraft', 'Video games', 'en'),
('Grand Theft Auto V', 'Video games', 'en'),
('The Legend of Zelda', 'Video games', 'en'),
('Elden Ring', 'Video games', 'en'),
('Fortnite', 'Video games', 'en'),
('Call of Duty', 'Video games', 'en'),
('The Last of Us', 'Video games', 'en'),
('Red Dead Redemption 2', 'Video games', 'en'),
('God of War', 'Video games', 'en'),
('Cyberpunk 2077', 'Video games', 'en'),
('Super Mario Odyssey', 'Video games', 'en'),
('League of Legends', 'Video games', 'en'),
('Valorant', 'Video games', 'en'),
('Hades', 'Video games', 'en'),
('Overwatch', 'Video games', 'en'),
('The Witcher 3', 'Video games', 'en'),
('Among Us', 'Video games', 'en'),
('Roblox', 'Video games', 'en'),
('Final Fantasy VII', 'Video games', 'en'),
('Halo Infinite', 'Video games', 'en');
