-- Insert 20 Spanish words for each of the 14 categories
INSERT INTO words (text, category, language) VALUES
-- Cine
('El Padrino', 'Cine', 'es'),
('Pulp Fiction', 'Cine', 'es'),
('Cadena Perpetua', 'Cine', 'es'),
('La Lista de Schindler', 'Cine', 'es'),
('El Caballero Oscuro', 'Cine', 'es'),
('Origen', 'Cine', 'es'),
('El Club de la Lucha', 'Cine', 'es'),
('Forrest Gump', 'Cine', 'es'),
('Matrix', 'Cine', 'es'),
('Uno de los Nuestros', 'Cine', 'es'),
('El Señor de los Anillos', 'Cine', 'es'),
('Star Wars: La Guerra de las Galaxias', 'Cine', 'es'),
('Parásitos', 'Cine', 'es'),
('Ciudadano Kane', 'Cine', 'es'),
('El Silencio de los Corderos', 'Cine', 'es'),
('Salvar al Soldado Ryan', 'Cine', 'es'),
('La Vida es Bella', 'Cine', 'es'),
('Psicosis', 'Cine', 'es'),
('Gladiator', 'Cine', 'es'),
('Casablanca', 'Cine', 'es'),

-- Futbolistas
('Lionel Messi', 'Futbolistas', 'es'),
('Diego Maradona', 'Futbolistas', 'es'),
('Cristiano Ronaldo', 'Futbolistas', 'es'),
('Pelé', 'Futbolistas', 'es'),
('Andrés Iniesta', 'Futbolistas', 'es'),
('Xavi Hernández', 'Futbolistas', 'es'),
('Iker Casillas', 'Futbolistas', 'es'),
('Sergio Ramos', 'Futbolistas', 'es'),
('Luis Suárez', 'Futbolistas', 'es'),
('Neymar Jr', 'Futbolistas', 'es'),
('Zinedine Zidane', 'Futbolistas', 'es'),
('Ronaldo Nazário', 'Futbolistas', 'es'),
('Ronaldinho', 'Futbolistas', 'es'),
('Luka Modrić', 'Futbolistas', 'es'),
('Karim Benzema', 'Futbolistas', 'es'),
('Kylian Mbappé', 'Futbolistas', 'es'),
('Vinícius Jr', 'Futbolistas', 'es'),
('Jude Bellingham', 'Futbolistas', 'es'),
('Emiliano Martínez', 'Futbolistas', 'es'),
('Pedri', 'Futbolistas', 'es'),

-- Equipos de fútbol
('Real Madrid', 'Equipos de fútbol', 'es'),
('FC Barcelona', 'Equipos de fútbol', 'es'),
('Atlético de Madrid', 'Equipos de fútbol', 'es'),
('Sevilla FC', 'Equipos de fútbol', 'es'),
('Athletic Club', 'Equipos de fútbol', 'es'),
('Real Betis', 'Equipos de fútbol', 'es'),
('Valencia CF', 'Equipos de fútbol', 'es'),
('River Plate', 'Equipos de fútbol', 'es'),
('Boca Juniors', 'Equipos de fútbol', 'es'),
('Flamengo', 'Equipos de fútbol', 'es'),
('Manchester City', 'Equipos de fútbol', 'es'),
('Liverpool', 'Equipos de fútbol', 'es'),
('Bayern de Múnich', 'Equipos de fútbol', 'es'),
('Inter de Milán', 'Equipos de fútbol', 'es'),
('AC Milan', 'Equipos de fútbol', 'es'),
('Juventus', 'Equipos de fútbol', 'es'),
('Paris Saint-Germain', 'Equipos de fútbol', 'es'),
('Borussia Dortmund', 'Equipos de fútbol', 'es'),
('Bayer Leverkusen', 'Equipos de fútbol', 'es'),
('Benfica', 'Equipos de fútbol', 'es'),

-- Personajes de Disney
('Mickey Mouse', 'Personajes de Disney', 'es'),
('Pato Donald', 'Personajes de Disney', 'es'),
('Goofy', 'Personajes de Disney', 'es'),
('Simba', 'Personajes de Disney', 'es'),
('Blancanieves', 'Personajes de Disney', 'es'),
('Cenicienta', 'Personajes de Disney', 'es'),
('La Sirenita', 'Personajes de Disney', 'es'),
('Aladdín', 'Personajes de Disney', 'es'),
('Bella', 'Personajes de Disney', 'es'),
('Mulán', 'Personajes de Disney', 'es'),
('Hércules', 'Personajes de Disney', 'es'),
('Pocahontas', 'Personajes de Disney', 'es'),
('Woody', 'Personajes de Disney', 'es'),
('Buzz Lightyear', 'Personajes de Disney', 'es'),
('Rayo McQueen', 'Personajes de Disney', 'es'),
('Elsa', 'Personajes de Disney', 'es'),
('Olaf', 'Personajes de Disney', 'es'),
('Stitch', 'Personajes de Disney', 'es'),
('Peter Pan', 'Personajes de Disney', 'es'),
('Maléfica', 'Personajes de Disney', 'es'),

-- Superhéroes
('Superman', 'Superhéroes', 'es'),
('Batman', 'Superhéroes', 'es'),
('Wonder Woman', 'Superhéroes', 'es'),
('Spider-Man', 'Superhéroes', 'es'),
('Iron Man', 'Superhéroes', 'es'),
('Capitán América', 'Superhéroes', 'es'),
('Thor', 'Superhéroes', 'es'),
('Hulk', 'Superhéroes', 'es'),
('Flash', 'Superhéroes', 'es'),
('Linterna Verde', 'Superhéroes', 'es'),
('Aquaman', 'Superhéroes', 'es'),
('Black Widow', 'Superhéroes', 'es'),
('Pantera Negra', 'Superhéroes', 'es'),
('Doctor Strange', 'Superhéroes', 'es'),
('Lobezno', 'Superhéroes', 'es'),
('Daredevil', 'Superhéroes', 'es'),
('Shazam', 'Superhéroes', 'es'),
('Supergirl', 'Superhéroes', 'es'),
('Flecha Verde', 'Superhéroes', 'es'),
('Deadpool', 'Superhéroes', 'es'),

-- Bandas de rock
('Héroes del Silencio', 'Bandas de rock', 'es'),
('Soda Stereo', 'Bandas de rock', 'es'),
('Mecano', 'Bandas de rock', 'es'),
('Extremoduro', 'Bandas de rock', 'es'),
('Marea', 'Bandas de rock', 'es'),
('Fito & Fitipaldis', 'Bandas de rock', 'es'),
('Maná', 'Bandas de rock', 'es'),
('Los Prisioneros', 'Bandas de rock', 'es'),
('Enanitos Verdes', 'Bandas de rock', 'es'),
('Molotov', 'Bandas de rock', 'es'),
('Cafe Tacvba', 'Bandas de rock', 'es'),
('El Cuarteto de Nos', 'Bandas de rock', 'es'),
('La Renga', 'Bandas de rock', 'es'),
('Mago de Oz', 'Bandas de rock', 'es'),
('Estopa', 'Bandas de rock', 'es'),
('Los Rodríguez', 'Bandas de rock', 'es'),
('Bunbury', 'Bandas de rock', 'es'),
('Pereza', 'Bandas de rock', 'es'),
('Los Fabulosos Cadillacs', 'Bandas de rock', 'es'),
('Zoé', 'Bandas de rock', 'es'),

-- Series de TV
('La Casa de Papel', 'Series de TV', 'es'),
('Breaking Bad', 'Series de TV', 'es'),
('Juego de Tronos', 'Series de TV', 'es'),
('Los Simpson', 'Series de TV', 'es'),
('Friends', 'Series de TV', 'es'),
('The Office', 'Series de TV', 'es'),
('Succession', 'Series de TV', 'es'),
('Better Call Saul', 'Series de TV', 'es'),
('Narcos', 'Series de TV', 'es'),
('Élite', 'Series de TV', 'es'),
('Paquita Salas', 'Series de TV', 'es'),
('Aquí no hay quien viva', 'Series de TV', 'es'),
('El Ministerio del Tiempo', 'Series de TV', 'es'),
('Cuéntame cómo pasó', 'Series de TV', 'es'),
('Vis a Vis', 'Series de TV', 'es'),
('Stranger Things', 'Series de TV', 'es'),
('The Mandalorian', 'Series de TV', 'es'),
('El Juego del Calamar', 'Series de TV', 'es'),
('Chernobyl', 'Series de TV', 'es'),
('The Bear', 'Series de TV', 'es'),

-- Famosos
('Rosalía', 'Famosos', 'es'),
('Penélope Cruz', 'Famosos', 'es'),
('Javier Bardem', 'Famosos', 'es'),
('Shakira', 'Famosos', 'es'),
('Antonio Banderas', 'Famosos', 'es'),
('Rafa Nadal', 'Famosos', 'es'),
('Pau Gasol', 'Famosos', 'es'),
('Bad Bunny', 'Famosos', 'es'),
('Karol G', 'Famosos', 'es'),
('Ibai Llanos', 'Famosos', 'es'),
('Ricky Martin', 'Famosos', 'es'),
('Jennifer Lopez', 'Famosos', 'es'),
('Pedro Almodóvar', 'Famosos', 'es'),
('Luis Miguel', 'Famosos', 'es'),
('C. Tangana', 'Famosos', 'es'),
('Aitana', 'Famosos', 'es'),
('Alejandro Sanz', 'Famosos', 'es'),
('Salma Hayek', 'Famosos', 'es'),
('Maluma', 'Famosos', 'es'),
('Úrsula Corberó', 'Famosos', 'es'),

-- Personajes históricos
('Cristóbal Colón', 'Personajes históricos', 'es'),
('Simón Bolívar', 'Personajes históricos', 'es'),
('Miguel de Cervantes', 'Personajes históricos', 'es'),
('Pablo Picasso', 'Personajes históricos', 'es'),
('Salvador Dalí', 'Personajes históricos', 'es'),
('Frida Kahlo', 'Personajes históricos', 'es'),
('Francisco de Goya', 'Personajes históricos', 'es'),
('Federico García Lorca', 'Personajes históricos', 'es'),
('Isabel la Católica', 'Personajes históricos', 'es'),
('Hernán Cortés', 'Personajes históricos', 'es'),
('Juana de Arco', 'Personajes históricos', 'es'),
('Napoleón Bonaparte', 'Personajes históricos', 'es'),
('Julio César', 'Personajes históricos', 'es'),
('Leonardo da Vinci', 'Personajes históricos', 'es'),
('Albert Einstein', 'Personajes históricos', 'es'),
('Mahatma Gandhi', 'Personajes históricos', 'es'),
('Nelson Mandela', 'Personajes históricos', 'es'),
('Marie Curie', 'Personajes históricos', 'es'),
('Isaac Newton', 'Personajes históricos', 'es'),
('Alejandro Magno', 'Personajes históricos', 'es'),

-- Héroes de Marvel
('Iron Man', 'Héroes de Marvel', 'es'),
('Spider-Man', 'Héroes de Marvel', 'es'),
('Capitán América', 'Héroes de Marvel', 'es'),
('Thor', 'Héroes de Marvel', 'es'),
('Viuda Negra', 'Héroes de Marvel', 'es'),
('Hulk', 'Héroes de Marvel', 'es'),
('Doctor Strange', 'Héroes de Marvel', 'es'),
('Pantera Negra', 'Héroes de Marvel', 'es'),
('Bruja Escarlata', 'Héroes de Marvel', 'es'),
('Ojo de Halcón', 'Héroes de Marvel', 'es'),
('Ant-Man', 'Héroes de Marvel', 'es'),
('Capitana Marvel', 'Héroes de Marvel', 'es'),
('Star-Lord', 'Héroes de Marvel', 'es'),
('Groot', 'Héroes de Marvel', 'es'),
('Visión', 'Héroes de Marvel', 'es'),
('Soldado de Invierno', 'Héroes de Marvel', 'es'),
('Halcón', 'Héroes de Marvel', 'es'),
('Lobezno', 'Héroes de Marvel', 'es'),
('Daredevil', 'Héroes de Marvel', 'es'),
('Masacre', 'Héroes de Marvel', 'es'),

-- Raperos
('Canserbero', 'Raperos', 'es'),
('Kase.O', 'Raperos', 'es'),
('Residente', 'Raperos', 'es'),
('Nach', 'Raperos', 'es'),
('Trueno', 'Raperos', 'es'),
('Wos', 'Raperos', 'es'),
('Duki', 'Raperos', 'es'),
('Quevedo', 'Raperos', 'es'),
('Bizarrap', 'Raperos', 'es'),
('ToteKing', 'Raperos', 'es'),
('Violadores del Verso', 'Raperos', 'es'),
('Bad Bunny', 'Raperos', 'es'),
('Mala Rodríguez', 'Raperos', 'es'),
('Ayax y Prok', 'Raperos', 'es'),
('Natanael Cano', 'Raperos', 'es'),
('Eladio Carrión', 'Raperos', 'es'),
('Anuel AA', 'Raperos', 'es'),
('Daddy Yankee', 'Raperos', 'es'),
('Don Omar', 'Raperos', 'es'),
('Vico C', 'Raperos', 'es'),

-- YouTubers
('Ibai Llanos', 'YouTubers', 'es'),
('El Rubius', 'YouTubers', 'es'),
('Aurónplay', 'YouTubers', 'es'),
('TheGrefg', 'YouTubers', 'es'),
('Luisito Comunica', 'YouTubers', 'es'),
('DjMaRiiO', 'YouTubers', 'es'),
('Vegetta777', 'YouTubers', 'es'),
('Willyrex', 'YouTubers', 'es'),
('Jordi Wild', 'YouTubers', 'es'),
('HolaSoyGerman', 'YouTubers', 'es'),
('Fernanfloo', 'YouTubers', 'es'),
('Coscu', 'YouTubers', 'es'),
('DrossRotzank', 'YouTubers', 'es'),

-- Marcas de coches
('Toyota', 'Marcas de coches', 'es'),
('SEAT', 'Marcas de coches', 'es'),
('Renault', 'Marcas de coches', 'es'),
('Volkswagen', 'Marcas de coches', 'es'),
('Ford', 'Marcas de coches', 'es'),
('Peugeot', 'Marcas de coches', 'es'),
('Hyundai', 'Marcas de coches', 'es'),
('Kia', 'Marcas de coches', 'es'),
('BMW', 'Marcas de coches', 'es'),
('Mercedes-Benz', 'Marcas de coches', 'es'),
('Audi', 'Marcas de coches', 'es'),
('Ferrari', 'Marcas de coches', 'es'),
('Lamborghini', 'Marcas de coches', 'es'),
('Porsche', 'Marcas de coches', 'es'),
('Tesla', 'Marcas de coches', 'es'),
('Nissan', 'Marcas de coches', 'es'),
('Honda', 'Marcas de coches', 'es'),
('Citroën', 'Marcas de coches', 'es'),
('Fiat', 'Marcas de coches', 'es'),
('Mazda', 'Marcas de coches', 'es'),

-- Videojuegos
('Minecraft', 'Videojuegos', 'es'),
('Grand Theft Auto V', 'Videojuegos', 'es'),
('The Legend of Zelda', 'Videojuegos', 'es'),
('Elden Ring', 'Videojuegos', 'es'),
('Fortnite', 'Videojuegos', 'es'),
('Super Mario Odyssey', 'Videojuegos', 'es'),
('The Witcher 3', 'Videojuegos', 'es'),
('The Last of Us', 'Videojuegos', 'es'),
('Red Dead Redemption 2', 'Videojuegos', 'es'),
('God of War', 'Videojuegos', 'es'),
('League of Legends', 'Videojuegos', 'es'),
('Valorant', 'Videojuegos', 'es'),
('Final Fantasy VII', 'Videojuegos', 'es'),
('Hollow Knight', 'Videojuegos', 'es'),
('Stardew Valley', 'Videojuegos', 'es'),
('Call of Duty', 'Videojuegos', 'es'),
('Cyberpunk 2077', 'Videojuegos', 'es'),
('Among Us', 'Videojuegos', 'es'),
('Roblox', 'Videojuegos', 'es'),
('Resident Evil 4', 'Videojuegos', 'es');
