name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

jobs:
  trigger-deploy:
    name: Trigger Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger lauti-deployments
        run: |
          curl -X POST https://api.github.com/repos/LautaroBlasco23/lauti-deployments/dispatches \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d '{"event_type":"deploy","client_payload":{"service":"impostor-backend"}}'